### ISSUE TITLE
Add option to not jump to the first search result immediately 

### ISSUE THREAD

**Issue by Narsail** [FacilMap/facilmap#111]
Would it be possible to add an option to not jump to the first search result immediately? I had the recent case that when searching for some POIs in New Zealand / Australia that the first search result was located in the US. In that case the map directly jumped there. Which somehow disrupted the the user flow.

**Comment by cdauth** [comment]
In FacilMap 3 I added an "auto-zoom" option to the search form. The setting is persisted in the browser.

You can try out the beta version of FacilMap 3 on [beta.facilmap.org](https://beta.facilmap.org/). Note that it is a temporary instance, any maps that you create or edit there will be removed at some point again. Please report any issues here on GitHub.

**Comment by cdauth** [comment]
FacilMap 3 now runs on [facilmap.org](https://facilmap.org/).
