### ISSUE TITLE
Unknown parameter errors in avoid_features

### ISSUE THREAD

**Issue by gadamiak** [FacilMap/facilmap#112]
Using some of parameters in avoid_features in the routing form returns error:

> Unknown parameter value '`parameter`' for 'avoid_features'.

The affected parameters are (for Car profile):

- Avoid paved roads (`pavedroads`)
- Avoid unpaved roads (`unpavedroads`)
- Avoid tracks (`tracks`)
- Avoid tunnels (`tunnels`)

**Comment by gadamiak** [comment]
Additionally for Mountain Bike profile the same for:

- Avoid hills (`hills`)

I expect there may be more specific to other profiles.

**Comment by cdauth** [comment]
These parameters seem to be not supported anymore by OpenRouteService, so I removed them in FacilMap 3.

You can try out the beta version of FacilMap 3 on [beta.facilmap.org](https://beta.facilmap.org/). Note that it is a temporary instance, any maps that you create or edit there will be removed at some point again. Please report any issues here on GitHub.

**Comment by gadamiak** [comment]
Thanks for info. Great to hear you keep working on FacilMap again! It's a great piece of software with lots of potential. I was worried it got abandoned.

**Comment by cdauth** [comment]
FacilMap 3 now runs on [facilmap.org](https://facilmap.org/).
