### ISSUE TITLE
Covid-19 monitoring site of people gathering.

### ISSUE THREAD

**Issue by Rio71x** [FacilMap/facilmap#113]
Dear support,
due to the Covid-19 emergency i'm working to a site that monitors the gatherings of peoples reported by users of my site.

I would like to have a confirmation of people gathering using 2 different  IP addresses (not the time and date).
I am using facilmap and the markers, the goal is to have for the same address reported,  the first marker yellow with label to be confirmed by other user , and the second in red with label confirmed.

Is it possible for you provide me support or implement a script in the following map ? :

https://facilmap.org/PUrKag53A9qwU9#

Is it possible to export that map ?

Thanks a lot for your time.

**Comment by cdauth** [comment]
Sorry, I don't understand what exactly you need.

How are markers added? How should the colour be changed? To what do you want to export the map?

**Comment by Rio71x** [comment]
Dear friend,
thanks a lot for your prompt support.

The markers added are only for test purposes.
Considering two users that claims that is present a people in gathering in the same address ...

The first reported marker should be yellow (With label to be confirmed by another user)
The second reported marker replace the first and should be red (With label confirmed).

If is not possible i would like to export that map for a joomla site.

Thanks so much! Have a nice evening.

**Comment by cdauth** [comment]
I still don't understand what you need.

You can either have users manually change the colour of the marker by changing the colour by hand or by defining a dropdown/checkbox form field that sets the colour to yellow/red depending on its state.

Or you can build an application around FacilMap that sets the marker colour automatically in reaction to what users are doing. You can use the [FacilMap client](https://github.com/FacilMap/facilmap2/tree/master/client) for this.

I don't understand what you mean by “export for a joomla site”. You can export the markers/lines on a map as GeoJSON, GPX or HTML table, but I don’t know if that helps you for your site. If you want to embed the map into your site, just use an iframe.

**Comment by Rio71x** [comment]
Hi Candid,
thanks a lot for you explanation.
Now the situation is clear for me that i am a beginner for building custom maps.
I will investigate about FacilMap client and the rest of your suggestions.
Have a nice weekend.
