### ISSUE TITLE
Refresh after line creation

### ISSUE THREAD

**Issue by rhalbheer** [FacilMap/facilmap#122]
It might be a PICNIC problem (Problem in Chair Not In Computer), then I apologize: Whenever I create and draw a line, after having supplied the properties, the "add" menu remains grey. I need to refresh the site in order to get the menu again.

**Comment by cdauth** [comment]
Which exact method do you use to add the line?

**Comment by rhalbheer** [comment]
Well, in the menu, I chose “Add” then “line”, drew it, closed with double click, the properties window opened, I chose close and routed it for bike.

**Comment by cdauth** [comment]
I see. This seems to be a bug.

As a workaround you can finish drawing the line by licking the "Finish" button instead of using double-click.

**Comment by rhalbheer** [comment]
True, this works
Thank you

**Comment by cdauth** [comment]
This is hopefully fixed in FacilMap 3. You can try out the beta version on [beta.facilmap.org](https://beta.facilmap.org/). Note that it is a temporary instance, any maps that you create or edit there will be removed at some point again. Please report any issues here on GitHub.

**Comment by cdauth** [comment]
FacilMap 3 now runs on [facilmap.org](https://facilmap.org/).
