### ISSUE TITLE
Please add CyclOSM layer

### ISSUE THREAD

**Issue by govvin** [FacilMap/facilmap#148]
Please consider adding CyclOSM, a cycling-oriented layer, and a nice alternative to OpenCycleMap. Check out: https://www.cyclosm.org/legend.html

The tile server url is https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png. Tiles can be reused under the general OpenStreetMap [tile usage policy](https://operations.osmfoundation.org/policies/tiles/).

CyclOSM also updates more frequently.

**Comment by cdauth** [comment]
Oops, I guess I forgot to install the update. It should be there now.
