### ISSUE TITLE
Better colors for a route selected area

### ISSUE THREAD

**Issue by TROMsite** [FacilMap/facilmap#183]
If I create a route, the color is blue like so many other routes. It does have a slight white outer glow, but I suggest to use a different color or allow users to select one. 

This is how it looks like now:
![image](https://user-images.githubusercontent.com/38043315/123549459-6de20900-d769-11eb-84ac-a2bb2ec76dc3.png)

**Comment by TROMsite** [comment]
I guess it depends what maps styles you have selected. With other maps it looks a lot better:
![image](https://user-images.githubusercontent.com/38043315/123549601-0e382d80-d76a-11eb-8b14-6409b02aaf04.png)

In any case, for the first example it would help to be able to color the route to another color.

**Comment by cdauth** [comment]
You can change the colour of individual lines using the "Edit line data" dialog.

You can also change the default colour for a line by editing its type.

Does this help?

**Comment by TROMsite** [comment]
Oh this is brilliant. I love Facilmap! Thanks a lot for all of your work. I can close this one ;)
