### ISSUE TITLE
Embed maps button

### ISSUE THREAD

**Issue by TROMsite** [FacilMap/facilmap#184]
I see that it is easy to embed a map https://docs.facilmap.org/developers/embed.html#options but for those who do not read the docs, could be great to have an embed button. Cheers!

**Comment by cdauth** [comment]
I was planning to introduce something like this as part of #165.

**Comment by cdauth** [comment]
There is now a Share dialog in the Tools menu where you can generate the code to embed FacilMap. Do you think that fulfills your use case?

**Comment by TROMsite** [comment]
It is wonderful! Thank you so much! Cannot wait for YNH to push the update!
