### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by tio-trom** [FacilMap/facilmap#185]
Is there an easy way to edit the CSS and customize the map a bit? If so what files should be edited? I am familiar with CSS.

**Comment by cdauth** [comment]
So far the only way to do this is to edit the source code and create a custom build. Some rough instructions how to do this can be found [here](https://docs.facilmap.org/developers/development/dev-setup.html).

Each component has its own `.scss` file, so you can edit the ones of the components that you want to customise.

**Comment by cdauth** [comment]
The next release will introduce a CUSTOM_CSS_FILE environment variable that will include the CSS file under the given path.
