### ISSUE TITLE
When saving a map view should also save the route

### ISSUE THREAD

**Issue by tio-trom** [FacilMap/facilmap#190]
Say I make a map + route + layers and POIs. I save it. But now I cannot see my saved route. Is that intentional or a bug? Cheers!

**Comment by cdauth** [comment]
It's intentional. You need to add the route as a line to persist it on the saved map.

I know that this is a bit confusing, since it's not really clear what is saved on the map and what is just displayed temporarily. I have not been able to find a way to improve this so far.

**Comment by tio-trom** [comment]
I see. Is it no possible to export the GPX tracks/routes to the server and attach that to the saved view?

**Comment by cdauth** [comment]
I'm not sure what exactly you mean. When you you save a route/track as a line on a collaborative map, the track is saved on the server. It can also be exported as a GPX from there.

A saved view only decides how a saved map is shown, not what is on the map. If a line is saved on the map, it will be shown as part of any saved view, unless that view explicitly hides it using a filter.

**Comment by tio-trom** [comment]
Ok. Likely I do not understand how this works. I was wondering why it cannot save the routes somehow...Can't you save a route as a line?

**Comment by cdauth** [comment]
Could you explain in more detail what exactly you are doing and what exactly you are trying to achieve?

**Comment by tio-trom** [comment]
I am creating a route, from point A to point B. I may add more stops on the way, markers and such. When I click to save the view I expect all that is on the map to be saved, but as far as I can tell, it will save the markers and map style and position, but not my route.

**Comment by cdauth** [comment]
What I'm not completely sure about is what do you mean by "creating a route". I assume you are using the route form to calculate a route and then drag it around.

Afterwards, if you click on "Add to map" and then "Line", this route will be persisted on the map.

**Comment by cdauth** [comment]
Here is an example: https://docs.facilmap.org/users/lines/#add-a-route-as-a-line

**Comment by cdauth** [comment]
Routes are only temporary, while lines are persisted on the map. The reason why there is this separation is that sometimes you want to calculate a route temporarily, for example to find out the distance between two markers that are persisted on the map or your location and a marker on the map, but you don't want to persist the route on the map for others to see (or might not even have permission to modify the map).

**Comment by tio-trom** [comment]
Ahhh I completely missed that and I've read the documentation. I didn't realize it. I am sorry. This is perfect. Damn you really made this map super useful and wonderful. Thank you so much! I will close this issue as it is not an "issue".

**Comment by tio-trom** [comment]
Maybe what I would suggest is that if anyone creates a route and then saves the view, ask them to add the route as a line on the map and save that too. together with markers and all that. Currently I only see the option to save POIs.

**Comment by cdauth** [comment]
That wouldn't make a lot of sense to me. The POIs are not saved on the map when you save a view. The view simply stores the view settings for the current map, and it can store which POI types you have enabled in the same way as it stores which map styles or filters you have enabled.

Saving markers and lines along with a view would create the impression that they are saved as part of the view, not of the whole map. But saved markers and lines are always part of the whole map.

**Comment by tio-trom** [comment]
I understand, makes sense. Thank you for the explanation!
