### ISSUE TITLE
Where to increase the waypoints limit?

### ISSUE THREAD

**Issue by tio-trom** [FacilMap/facilmap#191]
What file can I edit to increase the 50 limit?

**Comment by cdauth** [comment]
I'm not aware of such a limit. What route mode settings are you using?

**Comment by tio-trom** [comment]
I am using "go on foot" and "route details enabled" + "hiking", if that's what you were asking for.

**Comment by cdauth** [comment]
I just tried this out and wasn't able to get an error even with 60 waypoints. Is this still an issue?
