### ISSUE TITLE
Colored polygons

### ISSUE THREAD

**Issue by Nikkey13** [FacilMap/facilmap#207]
Is there any way to create colored polygons? Because when i import GeoJson file that contains a single colored polygon on map i get the same polygon but in default blue color.

**Comment by cdauth** [comment]
After adding a polygon from a GeoJSON file to a collaborative map (as a line, because FacilMap does not support polygons yet), you can edit the line data to adjust the colour.

As far as I know, there is no standardized way to store a colour in a GeoJSON file. Where did you get the GeoJSON file from? How is the colour stored in it?

**Comment by Nikkey13** [comment]
I wrote it in interactive tool geodjson.io. It looks like this, color is stored in properties:
 {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "longtitude": 34.23432523,
        "lantitude": -44.2343232,
        "stroke": "#555554",
        "stroke-width": 2,
        "stroke-opacity": 1,
        "fill": "#ffccаа",
        "fill-opacity": 0.5
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              73.49613189697266,
              44.042933431708875
            ],
            [
              73.54042053222656,
              44.042933431708875
            ],
            [
              73.54042053222656,
              44.076240300843935
            ],
            [
              73.49613189697266,
              44.076240300843935
            ],
            [
              73.49613189697266,
              44.042933431708875
            ]
          ]
        ]
      }
    }
  ]
}

**Comment by cdauth** [comment]
Good to know, it seems that several GeoJSON tools store the styling like that, so I can add support to FacilMap for this format at some point, but right now it's unfortunately not supported yet.

**Comment by Nikkey13** [comment]
Ok, thank you
