### ISSUE TITLE
Keep attributes of a layer

### ISSUE THREAD

**Issue by lost-geographer** [FacilMap/facilmap#216]
When I open a osm file I can read each point/line attribute (illustration below), but once I import them into the map they get stripped out...  Would there be a way to keep this data ?

By the way, thanks for this excellent app !

![Capture d’écran du 2022-03-08 11-58-40](https://user-images.githubusercontent.com/11869843/157225420-7c8e4a63-c6f4-4b9a-97be-e5b4e35826e2.png)

**Comment by cdauth** [comment]
I believe that if you define fields using “Add” → “Manage types”, the attributes should be imported properly. So for example for your Marker type you would add a field called “advertising”, and then when you import a point, the “advertising” attribute is imported from the point.

**Comment by lost-geographer** [comment]
Awesome !
