### ISSUE TITLE
Can I use docker setup without API keys?

### ISSUE THREAD

**Issue by xeruf** [FacilMap/facilmap#233]
https://docs.facilmap.org/developers/server/docker.html#docker-compose lists a few tokens for different features - will it run without those tokens if I do not need those features?

**Comment by cdauth** [comment]
The API keys are explained here: https://docs.facilmap.org/developers/server/config.html

The app will run without the API keys. However, if the Mapbox and OpenRouteService keys are not configured, the routing options will still be shown in the UI, but an error will be thrown when you try to calculate a route.

If you have a use case in mind where you only need straight lines, but no routing support, I could imagine to change the UI to only show the options that are actually available.

**Comment by cdauth** [comment]
All API keys are now optional, when the app is started without the Mapbox and ORS API keys, the routing options will be hidden from the UI.
