### ISSUE TITLE
Edit URL Lost 

### ISSUE THREAD

**Issue by FritzSi** [FacilMap/facilmap#235]
Hi !

I lost my edit URL of my FacilMap and can't edit or delete the map.
Is there an easy solution? I'm a complete beginner and only wanted to test FacilMap.

Thanks a lot!
Fritz

**Comment by cdauth** [comment]
Right now there is no recovery mechanism. All you can do is create a copy of the map (by exporting it as GeoJSON and importing everything on a new map), then you at least have an editable version of the map again.
