### ISSUE TITLE
Docu improvement for filters

### ISSUE THREAD

**Issue by georg-d** [FacilMap/facilmap#242]
In https://docs.facilmap.org/users/filter/

_Filters are only affect what you currently see on the map,_
is wrong grammer, instead e.g. 
_Filters do only affect what you currently see on the map,_

Currently, how to filter for checkbox state is not explained (true or true() or "true" or...). Idea: After
_If you have a field “Status” and want to show only map objects whose status is “Done”, the filter expression would be data.Status == "Done"._
add
If you have a checkbox field "Done" and want to show only map objects with ticked checkbox, the filter expression would be `prop(data, "Done") == "1"` while `"0"` would show only unticked.

 
 
 

In any map > [toolbox](https://docs.facilmap.org/users/ui/#toolbox) > Tools > Filter

_Field values (example: data.Description or prop(data, "Description")_
misses the closing bracket
_Field values (example: data.Description or prop(data, "Description"))_

**Comment by cdauth** [comment]
Thank you for these useful remarks!

I have added some documentation for this case. It will be published with the next release of FacilMap.

**Comment by georg-d** [comment]
Thank you for the updates. 

In https://docs.facilmap.org/users/filter/
_For example, to how only values where the checkbox field “Confirmed” is checked_
an s is missing, i.e. how  => show

In any map > [toolbox](https://docs.facilmap.org/users/ui/#toolbox) > Tools > Filter
Field values (example: data.Description or prop(data, "Description")) ).
now has one closing bracket too much 🤪
Field values (example: data.Description or prop(data, "Description"))

**Comment by cdauth** [comment]
Thank you, these should be fixed now.
