### ISSUE TITLE
In detail window of one line/marker, show it's type

### ISSUE THREAD

**Issue by georg-d** [FacilMap/facilmap#243]
When clicking a marker or line, it's details are shown (coordinates, note etc):
![grafik](https://github.com/FacilMap/facilmap/assets/45993293/3c27dc95-7d4a-4cc2-8daa-355bbc8d25a7) 
In here, also show the name of the type (e.g. "done" or "todo") that line/marker is contained in – like the pink text. Rationale: Users unfamiliar with a given map understand what a line stands for. More details in https://github.com/FacilMap/facilmap/discussions/241

**Comment by cdauth** [comment]
The type is now displayed next to the marker/line name if there is more than one marker/line type in the map.

For now it is only available in [FacilMap Beta](https://beta.facilmap.org/) and will become available on FacilMap with the next release. (Keep in mind that FacilMap Beta contains a copy of all the maps, but any changes that you make there will be lost with the next release.)

**Comment by georg-d** [comment]
Thank you, the implementation is IMHO easy to use & helpful 🙂
