### ISSUE TITLE
Public transportation not working

### ISSUE THREAD

**Issue by SecularSteve** [FacilMap/facilmap#244]
Tried to open it on mobile in all of the styles, it shows literally nothing.

**Comment by cdauth** [comment]
Hey, this is a known issue. The public transportation overlay is using [Openptmap](https://wiki.openstreetmap.org/wiki/Openptmap), which unfortunately is out of service. I haven't found a good replacement yet.

**Comment by cdauth** [comment]
I have now set up an own server for the Openptmap style, so it is available again on the map (for now only Germany, I'm in the process of importing the whole world).
