### ISSUE TITLE
Is it intentional that highway=no is rendered? (catchall highway=* rendering) 

### ISSUE THREAD

**Issue by matkoniecz** [FacilMap/facilmap#247]
See https://facilmap.org/#16/46.2401/13.5133/MpnW and https://www.openstreetmap.org/way/590994691

![screen02](https://github.com/FacilMap/facilmap/assets/899988/31a4338e-c6de-4bc2-8698-a15483350b50)

See https://wiki.openstreetmap.org/wiki/Tag:highway%3Dno and https://wiki.openstreetmap.org/wiki/Talk:Tag:highway%3Dno#%22Many_data_consumers_will_take_any_highway%3D%2A_to_mean_that_there_is_some_sort_of_highway%22

**Comment by matkoniecz** [comment]
I see that FacilMap is built from components, but I cannot really figure out should I redirect this report to some component (or maybe it is using now dead project)

**Comment by cdauth** [comment]
In the app under Help → About FacilMap you can see which service provides which layer. The Mapnik Water layer is provided by [FreieTonne](https://www.freietonne.de/).
