### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [FacilMap/facilmap#257]
https://hosted.weblate.org/projects/facilmap/#information
says AGPLv3-only, but I guess that is meant to be an oversight over not selecting AGPLV3-or-later?

It isn't outright specified in the repo, but doing so with "only" is limiting, and changing it down the road
would require negotiating with every translator.

Can be changed in

https://hosted.weblate.org/settings/facilmap/facilmap-frontend/
https://hosted.weblate.org/settings/facilmap/facilmap-server/
https://hosted.weblate.org/settings/facilmap/facilmap-utils/

**Comment by cdauth** [comment]
I wasn't sure what the impact of this would be, but keeping it open for later license updates makes sense! I have updated the settings.
