### ISSUE TITLE
Add option "Any" for POIs filter

### ISSUE THREAD

**Issue by Arcturuss** [FacilMap/facilmap#261]
Sometimes the pre-defined filters, for example shop types, are not enough, and there currently is no option to select all shops regardless of the shop type.

Yes, I know that I can write a custom query like `nwr["shop"~".*"]`, but not everyone knows overpass or OSM tags.

**Comment by cdauth** [comment]
Good suggestion! I've restructured the POI categories a bit and added an "All amenities", "All touristic places", "All sports facilities" and "All shops" POI type.
