### ISSUE TITLE
Search URL does not work

### ISSUE THREAD

**Issue by commonist** [FacilMap/facilmap#268]
Since a few weeks (or month?) the URL search does not work. This feature is documented in https://docs.facilmap.org/users/search/#configure-a-browser-search-engine.

E. g. opening the URL "https://facilmap.org/#q=Berlin" does not zoom to the city of Berlin, but starts somewhere else. This behaviour happens in the Surf-Browser and Chromium. This used to work for a long time. 
![2024-04-20-191300_956x933_scrot](https://github.com/FacilMap/facilmap/assets/1570922/a02afbc4-eceb-4d67-8680-7d6f90210db3)

**Comment by cdauth** [comment]
Oh, this was indeed quite broken. Thanks for the report! It should be fixed now.
