### ISSUE TITLE
Distinguish sport=horse_racing from sport=equestrian

### ISSUE THREAD

**Issue by Hufkratzer** [FacilMap/facilmap#286]
Regarding
https://github.com/FacilMap/facilmap/blob/859f6e7371ce5ae98e1e19f3685ae5ac84244e54/leaflet/src/overpass/overpass-presets.ts#L121

[sport=horse_racing](https://wiki.openstreetmap.org/wiki/Tag:sport%3Dhorse_racing) is not the same as [sport=equestrian](https://wiki.openstreetmap.org/wiki/Tag:sport%3Dequestrian). A racecourse would be tagged leisure=sports_centre + sport=horse_racing, a horse riding (equestrian) centre would (mostly) be tagged leisure=horse_riding (+ optionally sport=equestrian). Compare
- [Racecourse](https://wiki.openstreetmap.org/wiki/How_to_map_a#Racecourse_(horse_racing))
- [Riding centre](https://wiki.openstreetmap.org/wiki/How_to_map_a#Riding_centre_(equestrian))

A riding centre is not a racecourse and vice versa.

Therefore, I suggest removing sport=equestrian from the current query for horse racing and just use sport=horse_racing there.

I also wonder why the query doesn't search for relations, only for nodes and ways.

You could add a separate query for just nwr sport=equestrian, but I don't recommend that because you would get everything as POI that has that tag, every single riding arena, shops ([examples](https://facilmap.org/#18/51.06628/13.33468/Lima-OPTM-o_horseracing)) and even objects without any feature tag. Do you really want that? Do you want to show every object with a [sport tag](https://wiki.openstreetmap.org/wiki/Key:sport) as a POI, even without a corresponding feature tag? But this is a more general problem with most of your sport queries. I would rather add a query for horse riding centres (tag [leisure=horse_riding](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dhorse_riding).

**Comment by cdauth** [comment]
Most of the overpass queries were copied over from OpenPoiMap, and sometimes they are not accurate or up to date, so I'm always happy about suggestions there.

For now I have split up the POI type into two separate ones, horse racing (`nwr[sport=horse_racing]`) and horse riding (`(nwr[sport=equestrian];nwr[leisure=horse_riding];)`). You're right that this will also show shops for horse riding equipment, but I cannot think of a good way to exclude them. Personally I think showing a few unfitting POIs is better than missing a few fitting POIs, as it is meant as a way to find places and not as an exclusive and accurate list.
