### ISSUE TITLE
Support KMZ import

### ISSUE THREAD

**Issue by cdauth** [FacilMap/facilmap#47]

**Comment by Korb** [comment]
Currently, when trying to import created on Google My Maps kmz-file, I get an error message

> Parsing error
> The selected file could not be parsed.

**Comment by cdauth** [comment]
I've implemented basic support for KMZ, it can now be imported on facilmap.org. If you need support for any specific KMZ features, feel free to open issues for those.

**Comment by Korb** [comment]
> Error reading files. The operation was aborted.

`drive.google.com/file/d/15G0wd2pfp7w5qYKUuJVH4b5oy4P5-God/view`

**Comment by cdauth** [comment]
Thanks for the example file. It seems like the file does not contain the compressed file sizes (it was probably generated as a stream), so the code that I wrote fails to find the position of the contained KML file.

I have changed the code to use an external library instead, please try again.
