### ISSUE TITLE
"Tools" -> "Open File" menu item does nothing

### ISSUE THREAD

**Issue by jaanussepp** [FacilMap/facilmap#90]
Tried to start a collaborative map and import some track with "Tools" -> "Open File" menu item. Nothing happens. Tried GPX (both route and track versions) and KML. Tried Chrome, Opera and Internet Explorer browsers. Still nothing.

**Comment by cdauth** [comment]
Thanks for the report. This seems to have broken with the recent changes to the search/routing form. Will fix it as fast as possible.

**Comment by cdauth** [comment]
I installed a fix. There is still a minor problem with importing files (the part of the track that you click on is not selected in the route form), but the basic functionality should be back.

**Comment by olefs** [comment]
With which files does the "open file" function work?
I tried to upload a CSV file with one column containing the name of the markers and one containing latitude and longitude.
I got the Error "Some files could not be parsed."

**Comment by cdauth** [comment]
I think it currently works with GeoJSON, GPX, KML and OSM.

If you need CSV, feel free to open an issue for that, but I think that would be a larger feature, as it probably needs a designated dialog to customize which column needs what.
